<?php

namespace Drupal\nodeviewcount\Plugin\views\field;

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\Annotation\ViewsJoin;
use Drupal\views\Plugin\views\field\FieldPluginBase;
use Drupal\views\ResultRow;

/**
 * @ingroup views_field_handlers
 *
 * @ViewsField("node_view_count_count_of_views")
 */
class NodeViewCountCountOfViews extends FieldPluginBase {

  /**
   * {@inheritdoc}
   */
  public function query () {
    $this->ensureMyTable();
  }

  public function defineOptions () {
    //return parent::defineOptions(); // TODO: Change the autogenerated stub
  }

  public function clickSort ($order){
    //parent::clickSort($order); // TODO: Change the autogenerated stub
  }
}