# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: "module.test"
vagrant_machine_name: module
vagrant_ip: "192.168.88.88"

# Allow Drupal VM to be accessed via a public network interface on your host.
# Vagrant boxes are insecure by default, so be careful. You've been warned!
# See: https://docs.vagrantup.com/v2/networking/public_network.html
vagrant_public_ip: "10.2.0.44"

vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: ~/DrupalVM/Sites/module
    destination: /var/www/module
    type: nfs


drupal_build_makefile: false
drupal_build_composer: false
drupal_build_composer_project: false
drupal_install_site: false
drupal_core_path: "/var/www/module"
drupal_domain: "{{ vagrant_hostname }}"

# XDebug configuration. XDebug is disabled by default for better performance.
php_xdebug_default_enable: on
php_xdebug_coverage_enable: on
php_xdebug_remote_enable: on
php_xdebug_remote_connect_back: on
php_xdebug_idekey: "vagrant"

# Cron jobs are added to the vagrant user's crontab. Keys include name
# (required), minute, hour, day, weekday, month, job (required), and state.
drupalvm_cron_jobs:
  - name: "Drupal Cron"
    minute: "*/1"
    job: "{{ drush_path }} -r {{ drupal_core_path }} core-cron"
