<?php

namespace Drupal\node\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

class NoteSettings extends ConfigFormBase {

  /**
   * {@inheritdoc}
   */
  protected function getEditableConfigNames () {
    return ['node.settings'];
  }

  /**
   * {@inheritdoc}
   */
  public function getFormId () {
    return 'node_settings_form';
  }

  /**
   * {@inheritdoc}
   */
  public function buildForm (array $form, FormStateInterface $form_state) {
    /*
    $form['update'] = [
      '#type' => 'submit',
      '#value' => t('Update status'),
    ];
    $form['reset'] = [
      '#type' => 'submit',
      '#value' => t('Reset status')
    ];
*/
    return parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  public function submitForm (array &$form, FormStateInterface $form_state) {
    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
  }

}