<?php

use Drupal\Core\Render\BubbleableMetadata;

/**
 * Implements hook_token_info().
 */
function mailing_token_info () {
  $type = [
   'name' => t('Mailing token'),
   'description' => t('Mailing token description'),
  ];
  $allActiveUsers['allActiveUsers'] = [
    'name' => t('All active users'),
    'description' => t('All active users description')
  ];
  return [
    'types' => ['mailing' => $type],
    'tokens' => [
      'mailing' => [
        'all-active-users' => $allActiveUsers['all-active-users'],
      ]
      ,
    ],
  ];
}

/**
 * Implements hook_tokens().
 */
function mailing_tokens ($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];
  foreach ($tokens as $name => $original){
    switch ($name){
      case 'all-active-users':
        $query = Drupal::database()->select('users_field_data', 'u');
        $query->addField('u', 'name');
        $query->condition('u.status','1', '=');
        $users = $query->execute()->fetchCol();

        $result = '';
        foreach ($users as $user) {
          $result .= $user . '#rm#';
        }
        $result = substr($result, 0,-4);
        $replacements[$original] = $result;
        break;
    }
  }
  return $replacements;
}

/**
 * Implements hook_cron().
 */
function mailing_cron () {
  $queue = \Drupal::queue('send_message_queue');
  while ($item = $queue->claimItem()){
    \Drupal::service('plugin.manager.mail')->mail('smtp', 'smtp-test',
    $item->data['mail'], $item->data['toMail'] , $item->data['message']);
    $queue->deleteItem($item);
  }
}