<?php

/**
 * Implements hook_page_attachments().
 */
function message_page_attachments(array &$attachments) {
  $config = \Drupal ::config('message.settings');
  $attachments['#attached']['library'][] = 'message/modal_window';
  $attachments['#attached']['drupalSettings']['message']['width'] = $config -> get('width');
  $attachments['#attached']['drupalSettings']['message']['height'] = $config -> get('height');
  $attachments['#attached']['drupalSettings']['message']['background'] = $config -> get('background');
  $attachments['#attached']['drupalSettings']['message']['border'] = $config -> get('border');
  $attachments['#attached']['drupalSettings']['message']['borderColor'] = $config -> get('borderColor');
  $attachments['#attached']['drupalSettings']['message']['fontSize'] = $config->get('fontSize');
  $attachments['#attached']['drupalSettings']['message']['color'] = $config->get('color');
  $attachments['#attached']['drupalSettings']['message']['title'] = $config->get('title');
}

/**
 * Implements hook_theme_registry_alter().
 */
function message_theme_registry_alter(&$theme_registry) {
  $path = drupal_get_path('module', 'message') . '/templates';
  $theme_registry['status_messages']['theme paths'] = array(0 => $path);
  $theme_registry['status_messages']['theme path'] = $path;
  $theme_registry['status_messages']['path'] = $path;
  $theme_registry['status_messages']['template'] = 'window';
}