<?php
/**
 * @file
 * @see \Drupal\node\Tests\NodeQueryAlterTest
 * @see \Drupal\node\Tests\NodeAccessBaseTableTest
 */

use Drupal\Core\Session\AccountInterface;
use Drupal\node\Entity\NodeType;
use Drupal\node\NodeInterface;

/**
 *  Implements hook_node_access_records().
 */
function node_view_permissions_node_access_records(NodeInterface $node) {
  drupal_set_message('hook_node_access_records');
  $grants = [];
  // We only care about the node if it's published.
  // We don't want to override view published permissions.
  if ($node->isPublished()) {
    $grants[] = [
      'realm' => "view_any_{$node->getType()}_content",
      'gid' => 1,
      'grant_view' => 1,
      'grant_update' => 0,
      'grant_delete' => 0,
      'priority' => 0,
    ];
    $grants[] = [
      'realm' => "view_own_{$node->getType()}_content",
      'gid' => $node->getOwnerId(),
      'grant_view' => 1,
      'grant_update' => 0,
      'grant_delete' => 0,
      'priority' => 0,
    ];
  }
  return $grants;
}

/**
 * Implements hook_node_grants().
 */
function node_view_permissions_node_grants(AccountInterface $account, $op) {
  drupal_set_message('hook_node_grants');
  $grants = [];
  if ($op == 'view') {
    foreach (NodeType::loadMultiple() as $type) {
      $type_id = $type->id();
      if ($account->hasPermission("view any $type_id content")) {
        $grants["view_any_{$type_id}_content"] = [1];
      }
      if ($account->hasPermission("view own $type_id content")) {
        $grants["view_own_{$type_id}_content"] = [$account->id()];
      }
    }
  }
  return $grants;
}

/**
 * Implements hook_node_access().
 */
function node_view_permissions_node_access (NodeInterface $node, $op, AccountInterface $account) {
  drupal_set_message('hook_node_access');
  $type = is_string($node) ? $node : $node->getType();
  if (node_view_permissions_check_node_type_activation($type)) {
    if ($op == 'view') {
      if (user_access('view any ' . $type . ' content', $account) || (user_access('view own ' . $type . ' content', $account) && ($account->uid == $node->uid))) {
        if (!$node->status && !(user_access('view own unpublished content') && ($account->uid == $node->uid))) {
          return NODE_ACCESS_DENY;
        }
        return NODE_ACCESS_ALLOW;
      }
      if (!count(module_implements('node_grants'))) {
        return NODE_ACCESS_DENY;
      }
    }
  }

  //return NODE_ACCESS_IGNORE;
}
